### ISSUE TITLE
[Missing]: Windows XP Embedded for Point of Service

### ISSUE THREAD

**Issue by MicrosoftLover-MS** [UMSKT/PIDDatabase#13]
### Product information

Windows XP Embedded for Point of Service

### Product key

WQ3CY-2D7FC-TYKKP-MH6DH-BKTVD

### About box

![wepos](https://github.com/user-attachments/assets/faf1deea-bd20-4c5d-b5d1-c849d18ce3be)

### Download link

https://archive.org/download/ms-win-embedded-pos1-beta/1.0.0387.0_WEPOS_DISK1.iso

**Comment by MicrosoftLover-MS** [comment]
It's the final release of Windows Embedded for Point of Service. Tested on VMware.
https://betawiki.net/wiki/Windows_Embedded_for_Point_of_Service_build_387

**Comment by MicrosoftLover-MS** [comment]
Thank you for your work.

**Comment by thepwrtank18** [comment]
Got the right values, making an update now.
```json
    "0D": [
        {
            "Type": "Embedded",
            "PIDRange": [
                100,
                199
            ],
            "EvaluationDays": "125",
            "AcivationGraceDays": "2147483647"
        },
        {
            "Type": "Embedded",
            "PIDRange": [
                200,
                899
            ],
            "EvaluationDays": "2147483647",
            "AcivationGraceDays": "2147483647"
        }
    ],
```

Thank you!

**Comment by MSLoverMS** [comment]
You're welcome! I absolutely love this project!

**Comment by MSLoverMS** [comment]
@thepwrtank18  Note that the products are different because one key is used to license the Designer and the other is used to license the image you generate.

**Comment by MSLoverMS** [comment]
Forget what I just said. WEPOS is fine. Sorry!

**Comment by MSLoverMS** [comment]
Thank you for adding my work. I'm glad to be able to participate here!
