### ISSUE TITLE
[Missing]: Windows Embedded Standard 2009

### ISSUE THREAD

**Issue by MicrosoftLover-MS** [UMSKT/PIDDatabase#15]
### Product information

Windows Embedded Standard 2009

### Product key

Toolkit:      R269K-HVB6P-J9DF3-TG48H-QDKPD
Runtime:   P6PR3-26HG6-FH2KC-T8F89-8BPP6

### About box

Windows Embedded Standard 2009 Toolkit:
![wes09-toolkit](https://github.com/user-attachments/assets/27754b06-3a72-4e92-a38d-aabea1e79c84)
Windows Embedded Standard 2009 Runtime Image Licensing:
![wes09-image-licensing](https://github.com/user-attachments/assets/c8ef3187-3bf5-42a3-9920-36bd2c66298f)
Windows Embedded Standard 2009 Image:
![wes09-image](https://github.com/user-attachments/assets/475d8498-75a8-48c5-8eb8-e5497b125e74)

### Download link

https://files.dog/MSDN/Windows%20Embedded%20Standard/en_windows_embedded_standard_2009_x86_dvd_283454.iso

**Comment by MicrosoftLover-MS** [comment]
This keys are for perpetual licensing of Windows Embedded Standard 2009 products. Tested on VMware.
https://betawiki.net/wiki/Windows_Embedded_Standard_2009_build_1500_(RTM)

**Comment by MicrosoftLover-MS** [comment]
Thank you for your work.

**Comment by MSLoverMS** [comment]
Thank you so much!
