### ISSUE TITLE
[Missing]: Windows Compute Cluster Server 2003

### ISSUE THREAD

**Issue by MicrosoftLover-MS** [UMSKT/PIDDatabase#16]
### Product information

Windows Compute Cluster Server 2003 

### Product key

Retail:                 KFGK3-GR9B4-T4FF2-TKDQK-WC4BJ
Volume:     
Retail x64:  
Volume x64:       MD47V-X48M8-GK3PQ-3V3M2-PXMRM
### About box

Retail:
![wccs03rtl](https://github.com/user-attachments/assets/56ffe25f-83d3-4457-8476-48e763c9d6fb)
Volume:
Retail x64:
Volume x64:
![wccs03-vlk64](https://github.com/user-attachments/assets/a634f4d0-16cb-4fcc-8a57-820169f9b553)

### Download link

Retail:
https://files.dog/MSDN/Windows%20Server%202003%20R2/en_win_srv_2003_r2_standard_with_sp2_cd1_x13-04790.iso
https://files.dog/MSDN/Windows%20Server%202003%20R2/en_win_srv_2003_r2_standard_with_sp2_cd2_x13-68583.iso
Retail x64:

Volume:
Volume x64:
https://files.dog/MSDN/Windows%20Server%202003%20R2/en_win_srv_2003_r2_standard_x64_vl_cd1.iso
https://files.dog/MSDN/Windows%20Server%202003%20R2/en_win_srv_2003_r2_standard_x64_vl_cd2.iso

**Comment by MicrosoftLover-MS** [comment]
Windows Compute Cluster Server 2003 is based on Windows Server 2003 Standard Edition

**Comment by MicrosoftLover-MS** [comment]
Working to find Volume Licensing Edition. I'll update the request when found.

**Comment by MicrosoftLover-MS** [comment]
Found VLK x64

**Comment by MSLoverMS** [comment]
Found VLK x86:   HRXYC-PP8FB-CD43F-PQGQF-DP2PJ
![wccs03vlk](https://github.com/user-attachments/assets/27304900-a848-45e1-8684-821a37c7dcd9)

**Comment by MSLoverMS** [comment]
Anyway I'll create another request to have everything nice and tidy.

**Comment by MSLoverMS** [comment]
I opened a new one, please refer to that one.

**Comment by thepwrtank18** [comment]
Closed as duplicate

**Comment by MSLoverMS** [comment]
Yep! It was from the other account I lost.
