### ISSUE TITLE
Embedstigation: Windows NT 4.0 Embedded Edition

### ISSUE THREAD

**Issue by MSLoverMS** [UMSKT/PIDDatabase#19]
### Product information

Windows NT 4.0 Embedded Edition
The key is for the "evaluation" version. The complete version of the product is not available anymore nor anywhere, but with a simply registry trick on the generated image, you can convert it to the complete version. (More info will be available on a comment)
It's the only version of Windows NT 4 to use 25 letter product key (like 98 and NT 5) and the only one to use BINKs and CIDs (if I'm not mistaken).

### Product key

I don't know if you are interested in this product.

This is an "evaluation" product key and I have quotes for a reason. The Component Designer doesn't expire, I tried moving the clock to 2030 and the program still opens and makes images. With the registry trick the images generated still boot and work. The program otherwise is a fully functional version of the program. 
C3DFK-FK7QC-D2WJ8-PH6FR-HQM7Q
BINK: 0E CID: 0

The Component Designer doesn't work on a Windows NT 5.x environment, at least not with XP. Use NT 4.0 instead.

### About box

The Target Designer:
![nttd](https://github.com/user-attachments/assets/08790773-2114-45b6-a6b2-e69015ca0731)
Image Created:
![imagecreated](https://github.com/user-attachments/assets/e7e87cf7-0263-49e9-92d8-704c34767388)
1. Go to the image location:
![imgloc](https://github.com/user-attachments/assets/66cdc20f-b104-4fef-b48a-475a7f361e0c)
2. Go to WINNT\System32\config and look for a file named SYSTEM and SYSTEM.ALT
![s32cfg](https://github.com/user-attachments/assets/ac635018-d557-448c-9e68-cbce73ce4421)
3. Open regedt32.exe
![regedtedit](https://github.com/user-attachments/assets/22cf71e5-4d5b-4125-9dfb-da5fab8279d9)
4. Go to HKEY_LOCAL_MACHINE
![HKLM](https://github.com/user-attachments/assets/a5ed9bf8-3b49-4016-a7c9-d0aa07130d21)
5. Click Registry > Load Hive...
![loadhive](https://github.com/user-attachments/assets/47439314-fb57-4a46-9398-a99077a69add)
6. Go to the location where SYSTEM / SYSTEM.ALT were.
![load](https://github.com/user-attachments/assets/d714f3d6-f8d8-4be2-a6fc-b59a6b0aaae1)
7. Load SYSTEM and give it a name:
![name](https://github.com/user-attachments/assets/23119c51-2ca6-4f61-a0ee-41ab97c42fdc)
8. Go to  HKEY_LOCAL_MACHINE > [Your name] > ControlSet001 > Control > ProductOptions
![poptions](https://github.com/user-attachments/assets/08bf8ed9-1162-466b-b4d7-786c66a8df85)
9. Double click "ProductSuite"
![before](https://github.com/user-attachments/assets/f07605e6-f280-43ff-9327-f3ce206ff6a1)
10. Change "Embedded Class: Temporary" to "Embedded Class: Class 2"
![after](https://github.com/user-attachments/assets/b4110bd5-3656-4205-8f4b-79f235118354)
11. Unload SYSTEM hive.
12. Do the same with SYSTEM.ALT file.
![thesame](https://github.com/user-attachments/assets/93ffc06a-951f-4fc5-b590-63a2187c8948)
13. Unload SYSTEM.ALT hive.

---Proving "activation"
A. The NT Embedded Deployed Image on current date:
![currendateemb](https://github.com/user-attachments/assets/d175c498-31d8-42c9-b3af-3a3ff84143d3)
B. The NT Embedded Deployed Image on 2030:
![futuredate](https://github.com/user-attachments/assets/2e0a47d3-f91b-48ff-b63e-17e27bec11eb)
-We can see still works.
A. The Target Designer on current date:
![tdcurr](https://github.com/user-attachments/assets/5747bd82-3a1d-4fcb-a340-670f570a3cda)

B. The Target Designer still works and can create images in 2030:
![td2030](https://github.com/user-attachments/assets/8344773c-bc15-41f0-a11b-d36d240828f2)
--And that's it.

### Download link

https://archive.org/download/4.0.1381.1-x-86fre-axpfre-mipsfre-ppcfre-client-workstation-oem-en-us-1996-10-14-omni-tech-oem/4.0.1381.204_x86fre_client-embedded_oem_en-us.zip

**Comment by MSLoverMS** [comment]
I don't know if this is useful at all for you guys. But at least we learn something new.

**Comment by thepwrtank18** [comment]
Made a dedicated issue label for stuff like this. This is new.

**Comment by MSLoverMS** [comment]
Sorry, though it was interesting. At least I somewhat "archived" it.

**Comment by thepwrtank18** [comment]
Making an NT4 VM right now for testing.

**Comment by MSLoverMS** [comment]
I thought I was being an idiot! He-he.
Remember to edit both files (SYSTEM and SYSTEM.alt with regedt32.exe)
You need at least SP4 for NT4.

**Comment by MSLoverMS** [comment]
I don't know if it works in VBOX, though. In VMware Workstation it does.

**Comment by MSLoverMS** [comment]
@thepwrtank18 Does it work for you?

**Comment by thepwrtank18** [comment]
Still getting the VM set up. (VMware keeps mounting the VMware Tools ISO rather than the Service Pack 6 ISO I downloaded)

**Comment by MSLoverMS** [comment]
Ok! Good luck!

**Comment by MSLoverMS** [comment]
If it works, tell me please. Let's hope it's not only my machine.

**Comment by MSLoverMS** [comment]
The Embedded image only supports IDE by default and has no mouse. So the second disk must be IDE if that's the case.
You can add the mouse in Component Designer, the SCSI driver too if you want.

**Comment by MSLoverMS** [comment]
@thepwrtank18 Did you manage to get it running?

**Comment by MSLoverMS** [comment]
I'm still looking to the lost product Compute Cluster 2003 x64 retail key, I really don't know if it exists because I'm having a hard time.

**Comment by thepwrtank18** [comment]
Got SP6 and VMware Tools installed. Still have to install IE4 SP2, since that's a dependency

**Comment by MSLoverMS** [comment]
I installed the Active Desktop but it's not necessary. I can publish an SP4 ISO that has the ie4 setup if you want

**Comment by MSLoverMS** [comment]
Here it is: https://archive.org/download/office-2016-project-std-retail-16.0.9029.2167-32-bit-64-bit-en/Windows%20NT%204.0/Microsoft%20Windows%20NT%204.0%20Service%20Pack%204%20%284.00.1381.133%29%20%281998-12%29%20%5BEnglish%5D%20%28CD%29%20%5BX04-10659%5D.zip

Its a little big (770MB).

**Comment by MSLoverMS** [comment]
This is the Service Pack 4 for NT + IE4

**Comment by thepwrtank18** [comment]
Got IE4 SP2 installed, I'm at the Setup part of NT Embedded.

**Comment by MSLoverMS** [comment]
The key is on the readme file too. Probably it first opened when you inserted the CD.

**Comment by MSLoverMS** [comment]
@thepwrtank18 To create the image you have to keep the CD inserted. The files to generate it are in the CD.
The XP/WES09 setup copies the files needed to set up the image to the hard drive, NTe does not.

**Comment by MSLoverMS** [comment]
@thepwrtank18 Managed to do it?

**Comment by thepwrtank18** [comment]
Pre-Windows XP keys are pretty simple to find out how to reproduce, they don't really care about the Channel ID, just the BINK.

**Comment by MSLoverMS** [comment]
You're welcome! Glad to show my Windows "embedstigations" to someone!

**Comment by MSLoverMS** [comment]
@thepwrtank18 Let's see if I can find that "lost" key for Compute Cluster for you guys!
See you!
